name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]


jobs:
  webpage:
    runs-on: ubuntu-latest
    container: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install build requirements
      run: ./.install_build_requirements
    - name: Install NPM modules
      run: npm install
    - name: Build web frontend
      run: npm run release
    - name: Pack archive
      run: tar cfvz targets/webpage.tar.gz targets/www
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webpage
        path: targets/webpage.tar.gz
  package:
    needs: webpage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - # Ubuntu 16.04 x86
          distribution-id: ubuntu
          distribution-version: "16.04"
          cpu-architecture: x86
        - # Ubuntu 16.04 x86_64
          distribution-id: ubuntu
          distribution-version: "16.04"
          cpu-architecture: x86_64
        - # Ubuntu 18.04 x86
          distribution-id: ubuntu
          distribution-version: "18.04"
          cpu-architecture: x86
        - # Ubuntu 18.04 x86_64
          distribution-id: ubuntu
          distribution-version: "18.04"
          cpu-architecture: x86_64
        - # Ubuntu 18.04 arm64
          distribution-id: ubuntu
          distribution-version: "18.04"
          cpu-architecture: arm64
        - # Ubuntu 20.04 x86_64
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: x86_64
        - # Ubuntu 20.04 arm64
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 x86_64
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: x86_64
        - # Ubuntu 22.04 armhf
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: armhf
        - # Ubuntu 22.04 arm64
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
        - # Windows x86
          distribution-id: windows
          distribution-version: ""
          cpu-architecture: x86
        - # Windows x86_64
          distribution-id: windows
          distribution-version: ""
          cpu-architecture: x86_64
    container: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Download webpage
      # Use the old download-artifact v1 here. The newer v2 does not work with 32bit containers.
      uses: actions/download-artifact@v1
      with:
        name: webpage
    - name: Depack webpage
      run: tar fvxz webpage/webpage.tar.gz
    - name: Build artifact
      run: python3 build_artifact.py ${{ matrix.platform.distribution-id }} ${{ matrix.platform.distribution-version }} ${{ matrix.platform.cpu-architecture }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: |
          targets/webui-*.tar.gz
          targets/webui-*.zip
